name: Bug Report
description: Report a bug or issue with Kip
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide the following information to help us investigate.
  
  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Which operating system(s) are you using?
      multiple: true
      options:
        - Raspberry Pi OS
        - macOS
        - iOS
        - Windows
        - Linux
        - Android     
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you using?
      multiple: true
      options:
        - Chromium
        - Chrome
        - Safari
        - Edge
        - Firefox
        - Brave
        - Opera
        - Other
    validations:
      required: true
  
  - type: input
    id: kip-version
    attributes:
      label: KIP Version
      description: What version of Kip are you using (Found in Settings -> Options -> Connectivity)?
      placeholder: e.g., v2.5.1
    validations:
      required: true
  
  - type: input
    id: signalk-version
    attributes:
      label: Signal K Server Version
      description: What version of Signal K server are you using?
      placeholder: e.g., v2.5.1
    validations:
      required: false
  
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true
  
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened instead?
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots, logs, or error messages
      placeholder: Any additional information that might be helpful
    validations:
      required: false
